apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- crd.yaml
- namespace.yaml
- rbac.yaml
- deployment.yaml
- service.yaml
commonLabels:
  kustomize.component: pytorch-operator
images:
- name: gcr.io/kubeflow-images-public/pytorch-operator
  newName: 809251082950.dkr.ecr.us-west-2.amazonaws.com/pytorch-operator
  newTag: "0.1"
